-- Run this script while connected to the afno_ghar database.

BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(20) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,

  role VARCHAR(20) NOT NULL DEFAULT 'customer'
    CHECK (
      role IN (
        'customer',
        'admin',
        'worker',
        'delivery_staff'
      )
    ),

  status VARCHAR(20) NOT NULL DEFAULT 'active'
    CHECK (
      status IN (
        'active',
        'inactive',
        'banned'
      )
    ),

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS addresses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id INTEGER NOT NULL
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  province VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  municipality VARCHAR(100) NOT NULL,
  ward_number VARCHAR(20),
  street_address VARCHAR(255) NOT NULL,
  landmark VARCHAR(255),

  latitude NUMERIC(10, 8),
  longitude NUMERIC(11, 8),

  is_default BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  image_url VARCHAR(500),

  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  category_id INTEGER NOT NULL
    REFERENCES categories(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  name VARCHAR(150) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  description TEXT,

  base_price NUMERIC(12, 2) NOT NULL
    CHECK (base_price >= 0),

  stock_quantity INTEGER NOT NULL DEFAULT 0
    CHECK (stock_quantity >= 0),

  product_type VARCHAR(20) NOT NULL DEFAULT 'ready_made'
    CHECK (
      product_type IN (
        'ready_made',
        'custom_made',
        'both'
      )
    ),

  is_customizable BOOLEAN NOT NULL DEFAULT FALSE,
  is_rentable BOOLEAN NOT NULL DEFAULT FALSE,

  image_url VARCHAR(500),

  status VARCHAR(20) NOT NULL DEFAULT 'active'
    CHECK (
      status IN (
        'active',
        'inactive',
        'out_of_stock'
      )
    ),

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_products_category
ON products(category_id);

CREATE INDEX IF NOT EXISTS idx_products_status
ON products(status);

CREATE TABLE IF NOT EXISTS product_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  product_id INTEGER NOT NULL
    REFERENCES products(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  image_url VARCHAR(500) NOT NULL,
  alternative_text VARCHAR(255),

  is_primary BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  product_id INTEGER NOT NULL
    REFERENCES products(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  material_id INTEGER NOT NULL
    REFERENCES materials(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  additional_price NUMERIC(12, 2) NOT NULL DEFAULT 0
    CHECK (additional_price >= 0),

  is_available BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT uq_product_material
    UNIQUE (product_id, material_id)
);

CREATE TABLE IF NOT EXISTS colors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name VARCHAR(100) NOT NULL UNIQUE,
  hex_code VARCHAR(7),

  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT chk_colors_hex_code
    CHECK (
      hex_code IS NULL
      OR hex_code ~ '^#[0-9A-Fa-f]{6}$'
    )
);

CREATE TABLE IF NOT EXISTS product_colors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  product_id INTEGER NOT NULL
    REFERENCES products(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  color_id INTEGER NOT NULL
    REFERENCES colors(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  additional_price NUMERIC(12, 2) NOT NULL DEFAULT 0
    CHECK (additional_price >= 0),

  is_available BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT uq_product_color
    UNIQUE (product_id, color_id)
);

CREATE TABLE IF NOT EXISTS carts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id INTEGER NOT NULL UNIQUE
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  cart_id INTEGER NOT NULL
    REFERENCES carts(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  product_id INTEGER NOT NULL
    REFERENCES products(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  material_id INTEGER
    REFERENCES materials(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,

  color_id INTEGER
    REFERENCES colors(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,

  quantity INTEGER NOT NULL DEFAULT 1
    CHECK (quantity > 0),

  custom_length NUMERIC(10, 2),
  custom_width NUMERIC(10, 2),
  custom_height NUMERIC(10, 2),

  special_instructions TEXT,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  order_number VARCHAR(40) NOT NULL UNIQUE,

  user_id INTEGER NOT NULL
    REFERENCES users(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  address_id INTEGER NOT NULL
    REFERENCES addresses(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  order_type VARCHAR(20) NOT NULL DEFAULT 'ready_made'
    CHECK (
      order_type IN (
        'ready_made',
        'custom',
        'mixed',
        'rental'
      )
    ),

  order_status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (
      order_status IN (
        'pending',
        'confirmed',
        'advance_paid',
        'in_production',
        'ready_for_delivery',
        'out_for_delivery',
        'delivered',
        'cancelled'
      )
    ),

  subtotal NUMERIC(12, 2) NOT NULL
    CHECK (subtotal >= 0),

  customization_charge NUMERIC(12, 2)
    NOT NULL DEFAULT 0
    CHECK (customization_charge >= 0),

  delivery_charge NUMERIC(12, 2)
    NOT NULL DEFAULT 0
    CHECK (delivery_charge >= 0),

  discount_amount NUMERIC(12, 2)
    NOT NULL DEFAULT 0
    CHECK (discount_amount >= 0),

  total_amount NUMERIC(12, 2) NOT NULL
    CHECK (total_amount >= 0),

  advance_required NUMERIC(12, 2)
    NOT NULL DEFAULT 0
    CHECK (advance_required >= 0),

  remaining_amount NUMERIC(12, 2)
    NOT NULL DEFAULT 0
    CHECK (remaining_amount >= 0),

  estimated_delivery_date DATE,
  notes TEXT,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  order_id INTEGER NOT NULL
    REFERENCES orders(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  product_id INTEGER
    REFERENCES products(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,

  product_name VARCHAR(150) NOT NULL,
  selected_material VARCHAR(100),
  selected_color VARCHAR(100),

  quantity INTEGER NOT NULL
    CHECK (quantity > 0),

  unit_price NUMERIC(12, 2) NOT NULL
    CHECK (unit_price >= 0),

  customization_price NUMERIC(12, 2)
    NOT NULL DEFAULT 0
    CHECK (customization_price >= 0),

  custom_length NUMERIC(10, 2),
  custom_width NUMERIC(10, 2),
  custom_height NUMERIC(10, 2),

  special_instructions TEXT,

  item_total NUMERIC(12, 2) NOT NULL
    CHECK (item_total >= 0),

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  order_id INTEGER NOT NULL
    REFERENCES orders(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  payment_type VARCHAR(30) NOT NULL
    CHECK (
      payment_type IN (
        'advance',
        'remaining',
        'full_payment',
        'rental_deposit',
        'refund'
      )
    ),

  payment_method VARCHAR(30) NOT NULL
    CHECK (
      payment_method IN (
        'esewa',
        'khalti',
        'bank_transfer',
        'cash_on_delivery',
        'cash'
      )
    ),

  amount NUMERIC(12, 2) NOT NULL
    CHECK (amount >= 0),

  transaction_reference VARCHAR(150),

  payment_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (
      payment_status IN (
        'pending',
        'completed',
        'failed',
        'refunded'
      )
    ),

  paid_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_stages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name VARCHAR(100) NOT NULL UNIQUE,

  stage_order INTEGER NOT NULL UNIQUE
    CHECK (stage_order > 0),

  description TEXT
);

CREATE TABLE IF NOT EXISTS production_tracking (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  order_item_id INTEGER NOT NULL
    REFERENCES order_items(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  stage_id INTEGER NOT NULL
    REFERENCES production_stages(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  tracking_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (
      tracking_status IN (
        'pending',
        'in_progress',
        'completed',
        'delayed'
      )
    ),

  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,

  remarks TEXT,

  updated_by INTEGER
    REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS delivery_zones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  province VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  municipality VARCHAR(100),

  estimated_days INTEGER NOT NULL
    CHECK (estimated_days >= 0),

  delivery_charge NUMERIC(12, 2)
    NOT NULL DEFAULT 0
    CHECK (delivery_charge >= 0),

  is_serviceable BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_carts_updated_at ON carts;

CREATE TRIGGER trg_carts_updated_at
BEFORE UPDATE ON carts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_cart_items_updated_at
ON cart_items;

CREATE TRIGGER trg_cart_items_updated_at
BEFORE UPDATE ON cart_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;

CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS
trg_production_tracking_updated_at
ON production_tracking;

CREATE TRIGGER trg_production_tracking_updated_at
BEFORE UPDATE ON production_tracking
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO categories (
  name,
  description
)
VALUES
  (
    'Sofas',
    'Comfortable sofas and sectionals'
  ),
  (
    'Beds',
    'Beds and bedroom furniture'
  ),
  (
    'Tables',
    'Dining, coffee and office tables'
  ),
  (
    'Chairs',
    'Dining, lounge and office chairs'
  ),
  (
    'Wardrobes',
    'Storage and wardrobe furniture'
  )
ON CONFLICT (name) DO NOTHING;

INSERT INTO materials (
  name,
  description
)
VALUES
  (
    'Sal Wood',
    'Strong locally available hardwood'
  ),
  (
    'Sisau Wood',
    'Durable premium hardwood'
  ),
  (
    'Plywood',
    'Affordable engineered wood'
  ),
  (
    'MDF',
    'Smooth engineered fibreboard'
  ),
  (
    'Metal',
    'Strong metal construction'
  )
ON CONFLICT (name) DO NOTHING;

INSERT INTO colors (
  name,
  hex_code
)
VALUES
  ('Natural Brown', '#8B5A2B'),
  ('Dark Walnut', '#4A2C2A'),
  ('White', '#FFFFFF'),
  ('Black', '#000000'),
  ('Cream', '#FFFDD0')
ON CONFLICT (name) DO NOTHING;

INSERT INTO production_stages (
  name,
  stage_order,
  description
)
VALUES
  (
    'Order Confirmed',
    1,
    'Customer order has been confirmed'
  ),
  (
    'Design Approved',
    2,
    'Final furniture design has been approved'
  ),
  (
    'Materials Collected',
    3,
    'Required materials have been collected'
  ),
  (
    'Cutting',
    4,
    'Materials are being measured and cut'
  ),
  (
    'Assembly',
    5,
    'Furniture parts are being assembled'
  ),
  (
    'Polishing',
    6,
    'Furniture is being polished or painted'
  ),
  (
    'Quality Inspection',
    7,
    'Furniture is being checked'
  ),
  (
    'Ready for Delivery',
    8,
    'Furniture is ready for dispatch'
  )
ON CONFLICT (name) DO NOTHING;

INSERT INTO products (
  category_id,
  name,
  slug,
  description,
  base_price,
  stock_quantity,
  product_type,
  is_customizable,
  is_rentable,
  status
)
SELECT
  c.id,
  'Royal Velvet 3-Seater',
  'royal-velvet-3-seater',
  'Comfortable three-seater sofa with a strong wooden frame.',
  45000,
  10,
  'both',
  TRUE,
  TRUE,
  'active'
FROM categories c
WHERE c.name = 'Sofas'
ON CONFLICT (slug) DO NOTHING;

INSERT INTO products (
  category_id,
  name,
  slug,
  description,
  base_price,
  stock_quantity,
  product_type,
  is_customizable,
  is_rentable,
  status
)
SELECT
  c.id,
  'Modern Wooden Bed',
  'modern-wooden-bed',
  'Modern wooden double bed suitable for Nepali homes.',
  55000,
  5,
  'both',
  TRUE,
  FALSE,
  'active'
FROM categories c
WHERE c.name = 'Beds'
ON CONFLICT (slug) DO NOTHING;

INSERT INTO products (
  category_id,
  name,
  slug,
  description,
  base_price,
  stock_quantity,
  product_type,
  is_customizable,
  is_rentable,
  status
)
SELECT
  c.id,
  'Six-Seater Dining Table',
  'six-seater-dining-table',
  'Dining table designed for six people.',
  65000,
  4,
  'both',
  TRUE,
  TRUE,
  'active'
FROM categories c
WHERE c.name = 'Tables'
ON CONFLICT (slug) DO NOTHING;

COMMIT;